version: '3.9'

services:
  mysql_db:
    image: mysql:8
    restart: always
    ports:
      - 3307:3306
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: budget
      MYSQL_ROOT_PASSWORD: 12345678

  api: 
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      ACCESS_TOKEN_SECRET: w+/W7mc2/gMLQ9z3GU7ri0FpMaqEB1iMFRZHYTyx5So+jIzI46Qsm8nFevJLTRiQKr71Nb6QN6kTkdMOZZo2bg==
      REFRESH_TOKEN_SECRET: eBHgjx/03PghJK6oVqQxT5wxN//7Zd+18h4tDb0MRkX1pkgOZiTFKb0ASwZNB/Px+T81H1ieFEqvndL3n+FACQ==
      MAIL_TOKEN_SECRET: w7spHYG++VNfJyqs0C95bj9+ygrbPGCpWLegMNbh4JdZwwGx+pCN6qV78t+oOI8HwVGNbk2bGdH3GcteK7Fabw==
    depends_on:
      - mysql_db



volumes:
  mysql_db: {}
